In [90]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split  
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_wine
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier


wine=load_wine()
X =wine.data
Y = wine.target
X_train, X_test, y_train, y_test = train_test_split(X, Y, shuffle=True ,random_state=42) 

In [85]:
clf = GaussianNB().fit(X_train,y_train)

In [86]:
predicted = clf.predict(X_test)

In [87]:
predicted

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0, 2, 2, 1, 2, 0, 1, 1, 1,
       2])

In [88]:
acc=sum(predicted==y_test)/len(y_test)*100
print(acc)

100.0


Check Accuracy with K Fold

In [89]:
kfold = KFold(3,True,1)
for train, test in kfold.split(wine.target):
    #print(test)
   # print("TRAIN:", train, "TEST:", test)
    X_train, X_test = X[train], X[test]
    y_train, y_test = Y[train], Y[test]
    clf = GaussianNB().fit(X_train,y_train)
    predicted = clf.predict(X_test)
    acc=sum(predicted==y_test)/len(y_test)*100
    print(acc)



96.66666666666667
98.30508474576271
98.30508474576271


In [99]:
kfold = KFold(3,True,1)
for train, test in kfold.split(wine.target):
    X_train, X_test = X[train], X[test]
    y_train, y_test = Y[train], Y[test]
    for k in range(20):
        print(X_train)
        k = k+1
        neigh = KNeighborsClassifier(n_neighbors=k )
        neigh.fit(X_train, y_train)
        predicted = neigh.predict(X_test)
        acc=sum(predicted==y_test)/len(y_test)*100
        print("For K =",k," predicted accuracy =",acc)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
For K = 1  predicted accuracy = 70.0
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
For K = 2  predicted accuracy = 65.0
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+